Remove double quotes around variables inside of [[ ... ]]

diff --git a/Tools/live-multi-kernel b/Tools/live-multi-kernel
--- a/Tools/live-multi-kernel
+++ b/Tools/live-multi-kernel
@@ -249,7 +249,7 @@ main() {
     # Of course we want to do this as soon as possible
 
     # Do sanity checks on a user provided template directory
-    if [[ -n "$TEMPLATE_DIR" ]]; then
+    if [[ -n $TEMPLATE_DIR ]]; then
         test -d "$TEMPLATE_DIR" || fatal "Could not find template directory %s" "$TEMPLATE_DIR"
 
         local distro_template="${TEMPLATE_DIR%/}/$CONF_DISTRO"
@@ -264,11 +264,11 @@ main() {
 
     # Always let command line parameters over-ride whenever it makes sense
     # Figure out the ISO_DIR and then the KERNEL_DIR and BOOTLOAD_DIR
-    if [[ "$MODE" = "live" ]]; then
+    if [[ $MODE = "live" ]]; then
         : ${ISO_DIR:=/live/boot-dev}
         : ${SQFS_DIR:=/live/linux}
 
-    elif [[ "$MODE" = "live-usb"  ]]; then
+    elif [[ $MODE = "live-usb"  ]]; then
         test -d "$LIVE_USB" || fatal "Could not find live-usb directory %s" "$(pqw $LIVE_USB)"
         msg "Using live-usb at %s" "$(pq $LIVE_USB)"
         : ${ISO_DIR:=$LIVE_USB}
@@ -296,16 +296,16 @@ main() {
 
     # Figure out the SQFS_DIR for kernel modules and bootloader-data file.
     # Mount the linuxfs file (if needed) after we make the WORK_DIR.
-    if [[ "$MODE" = "live-usb" && -z "$SQFS_DIR" ]]; then
+    if [[ $MODE = "live-usb" && -z $SQFS_DIR ]]; then
         SQFS_DIR="$WORK_DIR/sqfs"
         # Only mount the linuxfs file if we are going to use what's in it
-        if [[ -z "$DATA_FILE" ]] || do_step_q initrd; then
+        if [[ -z $DATA_FILE ]] || do_step_q initrd; then
             SUDO=sudo
             [ $UID -eq 0 ] && SUDO=
             my_mount_sudo "$KERNEL_DIR/linuxfs" "$SQFS_DIR" -t squashfs -o loop,ro
         fi
 
-    elif [[ "$MODE" = "live" ]]; then
+    elif [[ $MODE = "live" ]]; then
         : ${SQFS_DIR:=/live/linux}
     fi
 
@@ -328,15 +328,15 @@ main() {
     : ${DISTRO:=$DISTRO_NAME-${DISTRO_VERSION}}
     : ${ASCII_CODE_NAME:=$CODE_NAME}
 
-    if [[ -z "$FULL_DISTRO_NAME" ]]; then
+    if [[ -z $FULL_DISTRO_NAME ]]; then
         : ${FULL_DISTRO_NAME:=${DISTRO}_$ISO_ARCH}
-        [[ -n "$FLAV" ]] && FULL_DISTRO_NAME=$FULL_DISTRO_NAME-$FLAV
+        [[ -n $FLAV ]] && FULL_DISTRO_NAME=$FULL_DISTRO_NAME-$FLAV
     fi
 
     : ${RELEASE_DATE:=$(date +"$DATE_FORMAT")}
 
      # Used for template files since core systems have different .cfg file templates
-    [[ "$FLAV" = "core" ]] && CORE_PREFIX="core-"
+    [[ $FLAV = "core" ]] && CORE_PREFIX="core-"
 
     local ABS_TITLE_POS=$TITLE_POS
     local ABS_SUB_TITLE_POS=$(add_pos "$ABS_TITLE_POS" "$SUB_TITLE_POS")
@@ -401,7 +401,7 @@ find_kernels() {
     local second=$(echo "$vm_info" | tail -n1)
 
     # Assign "Legacy" and "Modern" labels according the sort -V order
-    if [[ "$(echo "$first" | cut -f1)" = "$k_low" ]]; then
+    if [[ $(echo "$first" | cut -f1) = $k_low ]]; then
         KERNEL_LAB_0=$KERNEL_LAB_LOW
         KERNEL_LAB_1=$KERNEL_LAB_HIGH
     else
@@ -744,7 +744,7 @@ get_template_file() {
     local fname=$1
     local p  file
     for p in "$TEMPLATE_DIR" "${TEMPLATE_PATH[@]}"; do
-        [[ -z "$p" ]] && continue
+        [[ -z $p ]] && continue
         file="$p/$TEMPLATE_NAME/$CONF_DISTRO/$fname"
         test -e "$file" && break
     done
@@ -761,7 +761,7 @@ get_template_file() {
 need_template_file() {
     local var=$1  fname=$2
     local found=$(get_template_file "$fname")
-    [[ -z "$found" ]] && fatal "Could not find template file %s"  "$(pqw $fname)"
+    [[ -z $found ]] && fatal "Could not find template file %s"  "$(pqw $fname)"
     test -r "$found"  || fatal "Could not read template file %s"  "$(pqw $found)"
     vmsg "Using template file %s" "$(pq $found)"
     eval $var=\$found
@@ -782,7 +782,7 @@ template_copy() {
 # case we throw a fatal error.
 #------------------------------------------------------------------------------
 maybe_fatal() {
-    [[ -n "$STRICT" ]] && fatal "$@"
+    [[ -n $STRICT ]] && fatal "$@"
     Msg "$@"
     exit 0
 }
@@ -800,7 +800,7 @@ last_log_session() {
 # Unmount things under work directory if needed then delete the work directory.
 #------------------------------------------------------------------------------
 clean_up() {
-    [[ -n "$WORK_DIR" && -d "$WORK_DIR" ]] || return
+    [[ -n $WORK_DIR && -d $WORK_DIR ]] || return
 
     do_step_q cleanup || return
 
