Make make-efi-img adaptive so we waste less than 10 K of space.

diff --git a/Tools/make-efi-img b/Tools/make-efi-img
--- a/Tools/make-efi-img
+++ b/Tools/make-efi-img
@@ -21,8 +21,7 @@ boot/grub/grub.cfg"
 OUTPUT_FILE="boot/grub/efi.img"
 GRUB_CFG="boot/grub/grub.cfg"
 
-
-MARGIN=100  # in Kilobytes (60 failed on anti's system)
+MAX_MARGIN=500 # in Kilobytes
 
 usage() {
     local ret=${1:-0}
@@ -31,7 +30,6 @@ usage() {
 Usage: $ME <directory>
 
 Create a efi.img fat32 filesystem-on-a-file containing:
-
 $(echo "$INPUT_FILE_LIST" | sed "s/^/    /")
 Usage
     exit $ret
@@ -39,41 +37,55 @@ Usage
 
 main() {
     [ $# -eq 1 ] || usage
-    
+
     local dir=${1%/}
 
     test -d $dir || fatal "$dir is not a directory"
 
-    local file full size=0
+    local file full needed=0
     for file in $INPUT_FILE_LIST; do
         full=$dir/$file
-        size=$((size + $(duk_size $full)))
+        needed=$((needed + $(duk_size $full)))
     done
-    echo "Size: $size"
-    local full_size=$((size + MARGIN))
-    
-    local full_out="$dir/$OUTPUT_FILE"
-    dd if=/dev/zero of="$full_out" bs=1K count=$full_size
-    mkfs.fat -n "EFI IMAGE" "$full_out"
+    echo "Kilobytes needed: $needed"
 
-    local mp="$WORK_DIR/mp"
+    local margin  mp="$WORK_DIR/mp" img="$dir/$OUTPUT_FILE"
+    for margin in $(seq 10 10 $MAX_MARGIN); do
+        local size=$((needed + margin))
+        echo "Try size: $size  margin: $margin"
+        make_efi_img "$img" "$mp" "$INPUT_FILE_LIST" $size 2>/dev/null
+        local ret=$?
+        sudo umount "$mp"
+        rmdir "$mp"
+        rmdir "$WORK_DIR"
+        [ $ret -eq 0 ] || continue
+
+        echo -e "\n$ME created $img"
+        return 0
+    done
+    echo "$ME Failed!"
+    return 2
+}
+
+make_efi_img() {
+    local  img=$1  mp=$2  list=$3  size=$4
+
+    dd if=/dev/zero of="$img" bs=1K count=$size
+    mkfs.fat -n "EFI IMAGE" "$img" >/dev/null
+
     mkdir -p "$mp"
-    sudo mount -o loop "$full_out" "$mp"
+    sudo mount -o loop "$img" "$mp"
     local targ
-    for file in $INPUT_FILE_LIST; do
+    for file in $list; do
         full="$dir/$file"
         targ="$mp/$file"
-        sudo mkdir -p "$(dirname "$targ")"
-        sudo cp "$full" "$targ"
+        sudo mkdir -p "$(dirname "$targ")" || return 1
+        sudo cp "$full" "$targ"            || return 1
     done
 
     local full_grub="$mp/$GRUB_CFG"
     sudo sed -i "1 iset root=(hd0)" "$full_grub"
-    sudo umount "$mp"
-    rmdir "$mp"
-    rmdir "$WORK_DIR"
-
-    echo -e "\nCreated $full_out"
+    return 0
 }
 
 duk_size() {
