merge

diff --git a/Template/COMMON/squashfs/etc/init.d/cron b/Template/COMMON/squashfs/etc/init.d/cron
--- a/Template/COMMON/squashfs/etc/init.d/cron
+++ b/Template/COMMON/squashfs/etc/init.d/cron
@@ -1,12 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 # Start/stop the cron daemon.
 #
 ### BEGIN INIT INFO
 # Provides:          cron
 # Required-Start:    $remote_fs $syslog $time
 # Required-Stop:     $remote_fs $syslog $time
-# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
-# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
+# Should-Start:      $named slapd autofs ypbind nscd nslcd
+# Should-Stop:       $named slapd autofs ypbind nscd nslcd
 # Default-Start:     2 3 4 5
 # Default-Stop:
 # Short-Description: Regular background program processing daemon
@@ -16,19 +16,16 @@
 #                    security and more powerful configuration options.
 ### END INIT INFO
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-DESC="cron daemon"
-NAME=cron
-DAEMON=/usr/sbin/cron
-PIDFILE=/var/run/crond.pid
-SCRIPTNAME=/etc/init.d/"$NAME"
-DISABLED_CONF=/live/config/disabled
 
-test -f $DAEMON || exit 0
+test -f /usr/sbin/cron || exit 0
+
+PIDFILE=/var/run/crond.pid
+# In some systems the pidfile might be (incorrectly) set to /etc
+# if this pidfile is present, use it instead.
+[ -e /etc/cron.pid ] && PIDFILE=/etc/crond.pid
+[ -r /etc/default/cron ] && . /etc/default/cron
 
 . /lib/lsb/init-functions
-
-[ -r /etc/default/cron ] && . /etc/default/cron
 
 # Read the system's locale and set cron's locale. This is only used for
 # setting the charset of mails generated by cron. To provide locale
@@ -60,37 +57,56 @@ parse_environment ()
 
 # Parse the system's environment
 if [ "$READ_ENV" = "yes" ] ; then
+    export LANG LC_ALL LC_CTYPE TZ LC_COLLATE
     parse_environment
+    LC_COLLATE=C # Force collation sequence since ASCII is expected in regexps
 fi
+
 
 case "$1" in
 start)	log_daemon_msg "Starting periodic command scheduler" "cron"
-
-        me=${0##*/}
-        test -r $DISABLED_CONF && sed -r -i "s/^($me)$/# \1/" $DISABLED_CONF
-
-        start_daemon -p $PIDFILE $DAEMON $EXTRA_OPTS
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --name cron --startas /usr/sbin/cron -- $LSBNAMES $EXTRA_OPTS
         log_end_msg $?
 	;;
-stop)	test -r $DISABLED_CONF && grep -q "^${0##*/}$" $DISABLED_CONF && return 0
-        log_daemon_msg "Stopping periodic command scheduler" "cron"
 
-        killproc -p $PIDFILE $DAEMON
-        RETVAL=$?
-        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
-        log_end_msg $RETVAL
+
+stop)   # Bail early if "lean" was a boot param and there is no cron running
+        CMDLINE=${CMDLINE:-$(cat /proc/cmdline)}
+        for param in $CMDLINE; do
+            case "$param" in
+                lean|antiX=*[Ll]*|aX=*[Ll]*)               LEAN=true ;;
+                disable_srv=*[lL]*|disable_service=*[lL]*) LEAN=true ;;
+            esac
+        done
+        [ "$LEAN" ] &&  ! ps -u root -o cmd | grep -q ^/usr/sbin/cron && exit 0
+        log_daemon_msg "Stopping periodic command scheduler" "cron"
+        start-stop-daemon --stop --quiet --pidfile $PIDFILE --name cron
+        log_end_msg $?
         ;;
 restart) log_daemon_msg "Restarting periodic command scheduler" "cron" 
-        $0 stop
-        $0 start
+        start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE --name cron
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --name cron --startas /usr/sbin/cron -- $LSBNAMES $EXTRA_OPTS
+        log_end_msg $?
         ;;
 reload|force-reload) log_daemon_msg "Reloading configuration files for periodic command scheduler" "cron"
 	# cron reloads automatically
         log_end_msg 0
         ;;
 status)
-        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
-        ;;
+       log_action_begin_msg "Checking periodic command scheduler"
+       if pidofproc -p "$PIDFILE" >/dev/null; then
+            log_action_end_msg 0 "running"
+            exit 0
+       else
+           if [ -e "$PIDFILE" ]; then
+                log_action_end_msg 1 "failed to start"
+                exit 1
+           else
+                log_action_end_msg 0 "not running"
+                exit 3
+           fi
+       fi
+         ;;
 *)	log_action_msg "Usage: /etc/init.d/cron {start|stop|status|restart|reload|force-reload}"
         exit 2
         ;;
